# Generated by Django 5.2.4 on 2025-08-29 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                ("kcal", models.PositiveIntegerField(blank=True, null=True)),
                ("meals", models.PositiveIntegerField(blank=True, null=True)),
                ("meal_size", models.PositiveIntegerField(blank=True, null=True)),
                ("package_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "package_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "calculate_price",
                    models.CharField(
                        choices=[("on", "On"), ("off", "Off")],
                        default="off",
                        max_length=3,
                    ),
                ),
                (
                    "pet_icon",
                    models.CharField(
                        choices=[
                            ("cat_icon.png", "Cat"),
                            ("dog_icon.png", "Dog"),
                            ("other_icon.png", "Other"),
                        ],
                        default="other_icon.png",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
