# Generated by Django 5.2.4 on 2025-08-29 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calculator", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foods",
                to="calculator.pet",
            ),
        ),
        migrations.AddConstraint(
            model_name="pet",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_pet_per_owner"
            ),
        ),
    ]
